### ISSUE TITLE
Is it possible to run in multithread?

### ISSUE THREAD

**Issue by antonae** [rmsolgi/geneticalgorithm#3]
Hi, 

Is it possible to run it multithread, calling several target functions in parallel?

Thanks for the package!

Anton

**Comment by Mexflubber** [comment]
I would love this very much too !

**Comment by PasaOpasen** [comment]
@antonae @Mexflubber I will do it in my supported fork https://github.com/PasaOpasen/geneticalgorithm2

**Comment by PasaOpasen** [comment]
@antonae @Mexflubber it's done

**Comment by Harut0726** [comment]
@PasaOpasen Hello. I tried to run your fork and I noticed that 
```
model.run(set_function=ga.set_function_multiprocess(f)
```
works much slower than 
```
model.run()
```
What can be the reason?

**Comment by timbastin** [comment]
Here is a fork of this repository, which implements multithreading. Since this repository is not actively maintained, I would recommend using the one PasaOpasen created: https://github.com/PasaOpasen/geneticalgorithm2

I do not know, why @rmsolgi deleted their messages since they were already mentioning the fork as a solution.

**Comment by seb-kw** [comment]
@antonae & @Mexflubber - can definitely recommend to have a look at https://github.com/PasaOpasen/geneticalgorithm2 and @timbastin fork with multithreading!

I also can't understand why solutions are deleted ...

**Comment by rmsolgi** [comment]
This version does not do multithreading. you may do multithreading inside your function to speed up the code.
